class Main inherits IO {
  main(): SELF_TYPE {
		out_string("\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				abcdefghij\
				")
  };
};
